alias k="kubectl"
alias kc="kubectx"
alias kn="kubens"
alias h="helm"
alias tf="terraform"
alias a="ansible"
alias ap="ansible-playbook"
alias ls="eza --icons --group-directories-first"
alias ll="eza --icons --group-directories-first -l"
alias bp="boilerplate"
alias prx="proxmox-manager"

